import React, { createContext, useState, useEffect, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  es: {
    login_title: "Iniciar Sesión",
    login_user: "Usuario",
    login_pass: "Contraseña",
    login_btn: "Ingresar",
    location_placeholder: "Sede / Oficina",
    
    users_subtitle: "Gestiona los miembros de tu organización y su proceso de onboarding",
    users_add_title: "Agregar Nuevo Miembro",
    users_add_subtitle: "Añade un nuevo empleado o encargado a tu plataforma.",
    companies_subtitle: "Administración SaaS Multi-tenant.",
    
    role_admin: "Administrador RRHH",
    role_employee: "Empleado",
    role_superadmin: "Super Administrador",
    role_supervisor_onboarding: "Supervisor de Onboarding",
    role_responsable_area: "Responsable de Área",
    role_encargado_area: "Encargado de Área",
    
    sidebar_dashboard: "Dashboard",
    sidebar_procesos: "Mis Procesos",
    sidebar_plantillas: "Mis Plantillas",
    sidebar_talento: "Gestión de Talento",
    sidebar_equipo_onboarding: "Equipo de Onboarding",
    sidebar_alertas: "Centro de Alertas",
    sidebar_analitica: "Analítica",
    sidebar_empresas: "Empresas",
    sidebar_usuarios: "Gestión de Talento",
    sidebar_ajustes: "Ajustes",
    
    dashboard_title: "Dashboard",
    dashboard_subtitle: "Vista general del onboarding",
    dashboard_kpi_active: "Procesos Activos",
    dashboard_kpi_employees: "Empleados en Onboarding",
    dashboard_kpi_overdue: "Tareas Vencidas",
    dashboard_kpi_nps: "NPS Promedio",
    dashboard_kpi_progress_avg: "Progreso Promedio",
    dashboard_error_missing_company: "No se pudo identificar la empresa asociada a tu sesión.",
    dashboard_error_missing_user: "No se pudo identificar el usuario asociado a tu sesión.",
    dashboard_employee_status: "Estado de Empleados",
    dashboard_recent_alerts: "Alertas Recientes",
    dashboard_new_process: "Nuevo Proceso",
    analytics_title: "Reporte de Onboarding",
    analytics_subtitle: "Avance general de los procesos de onboarding de tu empresa.",
    analytics_company: "Empresa",
    analytics_session_company: "Empresa de sesión",
    analytics_from: "Desde",
    analytics_to: "Hasta",
    analytics_apply_filters: "Aplicar filtros",
    analytics_export: "Exportar",
    analytics_total_onboardings: "Total de onboardings",
    analytics_completed: "Completados",
    analytics_in_progress: "En curso",
    analytics_delayed: "Atrasados",
    analytics_average_days: "Promedio de días",
    analytics_no_average: "Sin datos",
    analytics_detail_title: "Detalle de onboardings",
    analytics_records: "registros",
    analytics_employee: "Empleado",
    analytics_process: "Proceso",
    analytics_role: "Rol",
    analytics_start_date: "Fecha inicio",
    analytics_end_date: "Fecha fin",
    analytics_status: "Estado",
    analytics_progress: "Progreso",
    analytics_tasks: "Tareas",
    analytics_total_tasks: "Total tareas",
    analytics_completed_tasks: "Tareas completadas",
    analytics_delayed_tasks: "Tareas atrasadas",
    analytics_delayed_short: "atrasadas",
    analytics_completion_days: "Días completitud",
    analytics_error_loading: "No se pudo cargar el reporte de onboarding.",
    
    portal_admin: "Portal Admin",
    portal_employee: "Portal Empleado",
    
    modal_ajustes_title: "Ajustes del Sistema",
    modal_ajustes_appearance: "Apariencia",
    modal_ajustes_language: "Idioma",
    theme_light: "Claro",
    theme_dark: "Oscuro",
    theme_system: "Sistema",
    
    btn_close: "Cerrar",
    btn_save: "Guardar",
    btn_cancel: "Cancelar",
    btn_delete: "Eliminar",
    btn_add: "Agregar",
    btn_edit: "Editar",
    btn_assign: "Asignar",
    btn_track: "Seguimiento",
    btn_complete: "Completar",
    
    table_id: "ID",
    table_name: "Nombre",
    table_email: "Email",
    table_role: "Rol",
    table_company: "Empresa",
    table_status: "Estado",
    table_actions: "Acciones",
    table_location: "Ubicación",
    table_tasks: "Tareas",
    table_process: "Proceso",
    
    status_active: "Activo",
    status_inactive: "Inactivo",
    status_all_records: "Todos",
    filter_record_status: "Filtrar por estado",
    
    msg_confirm_delete: "¿Estás seguro de que quieres eliminar este elemento?",
    msg_success_delete: "Eliminado con éxito",
    msg_error_generic: "Error al cargar los datos",
    msg_loading: "Cargando...",
    msg_no_data: "No hay datos disponibles",
    msg_success_assign: "✅ ¡Onboarding asignado exitosamente!",
    msg_error_assign: "❌ Error al asignar onboarding.",
    msg_success_complete: "✅ Tarea completada con éxito",
    employee_portal_title: "Mi Onboarding",
    employee_portal_welcome: "Bienvenido/a",
    employee_portal_process: "Proceso de onboarding",
    employee_portal_no_journey: "No tienes un proceso de onboarding asignado en este momento.",
    employee_portal_missing_email: "No encontramos un email asociado a tu sesión.",
    employee_portal_error: "No pudimos cargar tu portal de onboarding.",
    employee_portal_task_error: "Error al completar la tarea.",
    employee_portal_open_resource: "Abrir recurso",
    employee_portal_deadline: "Vence",
    employee_portal_overdue: "Atrasada",
    employee_portal_completing: "Completando...",
    
    // Procesos
    processes_kpi_total: "Procesos Totales",
    processes_kpi_progress: "En Progreso",
    processes_kpi_completed: "Completados",
    processes_role_view: "Vista de Rol",
    processes_col_employee: "Colaborador",
    processes_col_area: "Área",
    processes_col_role: "Rol",
    processes_col_progress: "Progreso",
    processes_col_start: "Fecha Inicio",
    processes_col_end: "Fecha Fin",
    processes_col_location: "Ubicación",
    processes_col_actions: "Acciones",
    processes_btn_detail: "Ver Detalle",
    processes_modal_title: "Progreso de",
    processes_modal_task: "Tarea",
    processes_modal_status: "Estado",
    processes_modal_evidence: "Evidencia",
    processes_modal_completed: "Completada",
    processes_modal_pending: "Pendiente",
    processes_modal_download: "Descargar Evidencia",
    processes_modal_no_evidence: "Sin evidencia",
    processes_modal_no_journey: "No hay un proceso de onboarding activo asignado a este colaborador.",
    processes_empty_state: "No hay procesos de onboarding activos en este momento",
    processes_loading: "Cargando procesos...",
    
    // Filtros de usuarios
    filter_name: "Filtrar por Nombre",
    filter_email: "Filtrar por Email",
    filter_role: "Filtrar por Rol",
    filter_onboarding_status: "Filtrar por Estado de Onboarding",
    filter_all_statuses: "Todos los estados",
    filter_unassigned: "Sin Asignar",
    filter_in_progress: "En Proceso",
    filter_completed: "Completado",
    users_showing_count: "Mostrando",
    users_showing_of: "de",
    users_showing_users: "usuarios",
    users_per_page: "Usuarios por página:",
    users_page_indicator: "Página",
    users_page_of: "de",
    
    // Formulario de empresas
    company_new_title: "Nueva Empresa",
    company_edit_title: "Editar Empresa",
    company_country: "País",
    company_region_chile: "Región",
    company_region_mexico: "Estado",
    company_region_colombia: "Departamento",
    company_region_argentina: "Provincia",
    company_region_peru: "Departamento",
    company_region_default: "Región/Estado",
    company_city_commune: "Comuna / Ciudad",
    company_city_commune_placeholder: "Escribe la comuna o ciudad...",
    company_delete_confirm: "¿Estás seguro de que deseas eliminar esta empresa? Esta acción no se puede deshacer.",
    company_delete_success: "Empresa eliminada exitosamente",
    processes_subtitle: "Control y seguimiento de procesos de inducción y onboarding.",
    processes_admin_view: "Visualizando todos los procesos de onboarding de la empresa.",
    processes_supervisor_view: "Visualizando procesos bajo tu supervisión directa.",
    processes_encargado_view: "Visualizando procesos del área de:",
    processes_user_id: "Usuario ID",
    location_remote: "Remoto",
    processes_modal_progress_general: "Progreso General",
    processes_group_custom: "Procesos Personalizados / Sin Plantilla",
    processes_btn_delete: "Eliminar Proceso",
    processes_custom_desc: "Jornadas individuales sin plantilla base o con plantilla eliminada",
    processes_no_desc: "Sin descripción disponible",
    processes_colaborador: "colaborador",
    processes_colaboradores: "colaboradores",
    filter_name_placeholder: "Buscar nombre...",
    filter_email_placeholder: "Buscar email...",
    filter_all_roles: "Todos los roles",
    btn_previous: "Anterior",
    btn_next: "Siguiente",
    stage_label: "Etapa",
    label_area: "Área",
    label_location: "Ubicación",
    label_country: "País",
    label_city: "Ciudad",
    label_commune: "Comuna",
    label_office_branch: "Sucursal / Oficina",
    btn_new_area: "+ Nueva Área",
    btn_delete_area: "Eliminar Área",
    placeholder_area_name: "Nombre del área...",
    select_area_placeholder: "-- Seleccionar Área --",
    select_office_placeholder: "-- Seleccionar Sucursal --",
    btn_new_office: "+ Nueva",
    placeholder_office_name: "Nombre de sucursal...",
    placeholder_country: "ej: Chile",
    placeholder_city: "ej: Santiago",
    placeholder_commune: "ej: Providencia",
    placeholder_password_optional: "Dejar vacío para no cambiar",
    label_password_optional: "Contraseña (Opcional)",
    btn_assign_employee: "Asignar Empleado",
    assign_onboarding_title: "Asignar Onboarding",
    assign_onboarding_to: "Para",
    warning_label: "Advertencia",
    warning_active_journey: "Este empleado ya cuenta con un proceso de onboarding activo. Puedes asignarle un nuevo proceso de todas formas para enlazar etapas.",
    table_template: "Plantilla",
    label_mentor_supervisor: "Mentor / Supervisor",
    select_template_placeholder: "Seleccionar plantilla...",
    select_supervisor_placeholder: "Seleccionar supervisor...",
    btn_confirm_journey: "Confirmar Proceso",
    assign_employee_supervise_title: "Asignar Empleado a Supervisar",
    supervisor_area_label: "Área del Supervisor",
    no_area_label: "Sin Área",
    select_employee_area_placeholder: "Selecciona un empleado de tu área...",
    assign_supervisor_help_text: "Solo aparecen empleados activos de la misma área que cuentan con un proceso de onboarding.",
    msg_error_no_active_journey: "El empleado seleccionado no tiene un proceso activo.",
    msg_success_assign_supervisor: "Supervisor asignado con éxito.",
    msg_error_assign_supervisor: "Error al asignar supervisor.",
    users_edit_title: "Editar Usuario",
    users_edit_subtitle: "Actualiza los detalles del perfil del usuario.",
    users_no_filter_match: "No se encontraron usuarios con los filtros aplicados",
    error_create_office: "Error al crear la sucursal",
    error_create_area: "Error al crear el área",
    error_delete_area: "Error al eliminar el área",
    confirm_delete_area: "¿Estás seguro de eliminar esta área?",
    confirm_delete_user: "¿Estás seguro de que deseas eliminar a este usuario?",
    error_create_user: "Error al crear el usuario.",
    error_update_user: "Error al actualizar el usuario.",
    error_delete_user: "Error al eliminar el usuario.",
    msg_user_create_success: "Usuario creado con éxito.",
    msg_user_update_success: "Usuario actualizado con éxito.",
    msg_user_delete_success: "Usuario eliminado con éxito.",
    table_document: "Documento",
    msg_no_file: "Sin archivo",
    select_company_placeholder: "Seleccionar Empresa...",
    label_parent_template: "Proceso anterior vinculante",
    option_none_parent_template: "Ninguno (Proceso Inicial)",
    help_parent_template: "Permite encadenar onboardings mayores a 31 días.",
    error_save_template: "Error al guardar la plantilla",
    template_edit_title: "Editar Plantilla de Onboarding",
    template_new_title: "Nueva Plantilla de Onboarding",
    template_settings_title: "Ajustes de Plantilla",
    template_name_label: "Nombre de Plantilla",
    btn_save_template: "Guardar Plantilla",
    onboarding_steps_title: "Pasos de Onboarding",
    btn_add_step: "Agregar Paso",
    placeholder_task_title: "Título de la tarea (ej: Reunión de Bienvenida)",
    placeholder_resource_url: "Enlace al Documento o Video (Ej. Drive, YouTube)",
    placeholder_task_description: "Breve descripción de lo que debe hacer el empleado...",
    placeholder_sla_days: "SLA (días)",
    label_sla_days: "Días máximos para completar esta etapa (1-365). Vacío = sin fecha límite.",
    label_evidence_mandatory: "¿El empleado debe subir evidencia obligatoriamente para completar esta tarea?",
    btn_move_up: "Subir",
    btn_move_down: "Bajar",
    task_type_read_text: "Leer Texto (Bienvenida)",
    task_type_read_document: "Ver Documento / Enlace externo",
    task_type_watch_video: "Ver Video",
    task_type_upload_document: "Subir Archivo (Empleado)",
    error_delete_company: "Error al eliminar la empresa. Asegúrate de que no queden usuarios o procesos asociados a esta empresa.",
    mobile_access_title: "Acceso Empleado",
    mobile_email_label: "Email de la Empresa",
    mobile_btn_enter: "Entrar al Onboarding",
    mobile_user_not_found: "Usuario no encontrado o error de conexión",
    mobile_task_completed_success: "✅ Tarea completada con éxito",
    mobile_task_completed_error: "Error al completar la tarea",
    mobile_default_description: "Por favor completa esta etapa para continuar.",
    mobile_btn_watch_video: "📺 Ver Video",
    mobile_btn_open_resource: "📖 Abrir Recurso",
    mobile_upload_evidence_label: "Subir documento (PDF, JPG, PNG)",
    mobile_task_completed_badge: "✅ Tarea completada",
    mobile_status_uploading: "Subiendo...",
    mobile_status_completing: "Completando...",
    mobile_btn_complete: "Completar",
    mobile_btn_back_web: "← Volver a vista web",
    mobile_status_completed: "Completada",
    mobile_status_overdue: "Atrasada",
    mobile_status_pending: "Pendiente",
    mobile_label_due: "Vence:",
    mobile_btn_open_task: "Abrir Tarea",
    mobile_nav_home: "Inicio",
    mobile_nav_tasks: "Tareas",
    mobile_nav_files: "Archivos",
    mobile_nav_profile: "Perfil",
    mobile_greeting: "Hola",
    mobile_onboarding_at: "Onboarding en",
    error_invalid_credentials: "Credenciales inválidas",
    badge_overdue: "Vencida",
    badge_completed: "Completada",
    badge_pending: "Pendiente",
    dashboard_task_vence: "Vence",
    dashboard_tasks_pendientes: "Tareas Pendientes",
    dashboard_progreso_general: "Progreso General",
    dashboard_detalles_proceso: "Detalles del Proceso",
    dashboard_empleado: "Empleado",
    dashboard_rol: "Rol",
    dashboard_progreso: "Progreso",
    dashboard_tareas_proceso: "Tareas del Proceso",
    dashboard_no_tareas: "No hay tareas registradas para este proceso.",
    dashboard_mas_tareas: "tareas más",
    dashboard_todas_completadas: "¡Todas las tareas completadas!",
    dashboard_no_onboardings: "No hay procesos de onboarding en progreso.",
    alert_overdue_task: "Tarea Vencida",
    alert_type_sla_expired: "SLA vencido",
    alert_time_overdue: "Vencida",
    alert_time_recent: "Reciente",
    alert_no_pending: "Sin alertas pendientes.",
    alerts_subtitle: "Seguimiento de tareas vencidas y alertas atendidas",
    alerts_refresh: "Actualizar",
    alerts_active: "Activas",
    alerts_history: "Historial",
    alerts_search: "Buscar alerta",
    alerts_employee: "Empleado",
    alerts_task: "Tarea",
    alerts_deadline: "Fecha límite",
    alerts_days_overdue: "Días de retraso",
    alerts_generated_at: "Generada",
    alerts_status: "Estado",
    alerts_pending: "Pendiente",
    alerts_attended: "Atendida",
    alerts_attend: "Atender",
    alerts_days: "día(s)",
    alerts_no_history: "No hay alertas atendidas en el historial.",
    alerts_error_load: "No se pudieron cargar las alertas.",
    alerts_error_attend: "No se pudo atender la alerta.",
    alerts_error_user: "No se pudo identificar el usuario para atender la alerta.",
    filter_by_area: "Filtrar por Área",
    all_areas: "Todas las Áreas",
    modal_ajustes_tab_preferences: "Preferencias",
    modal_ajustes_tab_areas: "Áreas de la Empresa",
    modal_ajustes_tab_offices: "Sucursales / Oficinas",
    select_country_placeholder: "-- Seleccionar País --",
    select_city_placeholder: "-- Seleccionar Ciudad/Estado --",
    loading_areas: "Cargando áreas...",
    no_areas_configured: "No hay áreas configuradas para tu empresa.",
    loading_offices: "Cargando sucursales/oficinas...",
    no_offices_configured: "No hay sucursales/oficinas configuradas.",
    confirm_delete_office: "¿Estás seguro de que quieres eliminar esta sucursal/oficina?",
    error_load_areas: "Error al cargar las áreas de la empresa.",
    error_update_area: "Error al actualizar el área.",
    error_load_offices: "Error al cargar las sucursales/oficinas de la empresa.",
    error_delete_office: "Error al eliminar la sucursal/oficina.",
    error_update_office: "Error al actualizar la sucursal/oficina.",
  },
  en: {
    login_title: "Sign In",
    login_user: "Username",
    login_pass: "Password",
    login_btn: "Sign In",
    location_placeholder: "Site / Location",
    
    users_subtitle: "Manage your organization members and their onboarding journey",
    users_add_title: "Add New Member",
    users_add_subtitle: "Add a new employee or manager to your platform.",
    companies_subtitle: "SaaS Multi-tenant administration.",
    
    role_admin: "Admin HR",
    role_employee: "Employee",
    role_superadmin: "Super Admin",
    role_supervisor_onboarding: "Onboarding Supervisor",
    role_responsable_area: "Area Responsible",
    role_encargado_area: "Area Manager",
    
    sidebar_dashboard: "Dashboard",
    sidebar_procesos: "My Processes",
    sidebar_plantillas: "My Templates",
    sidebar_talento: "Talent Management",
    sidebar_equipo_onboarding: "Onboarding Team",
    sidebar_alertas: "Alerts",
    sidebar_analitica: "Analytics",
    sidebar_empresas: "Companies",
    sidebar_usuarios: "Users",
    sidebar_ajustes: "Settings",
    
    dashboard_title: "Dashboard",
    dashboard_subtitle: "Onboarding Overview",
    dashboard_kpi_active: "Active Processes",
    dashboard_kpi_employees: "Employees in Onboarding",
    dashboard_kpi_overdue: "Overdue Tasks",
    dashboard_kpi_nps: "Average NPS",
    dashboard_kpi_progress_avg: "Average Progress",
    dashboard_error_missing_company: "The company associated with your session could not be identified.",
    dashboard_error_missing_user: "The user associated with your session could not be identified.",
    dashboard_employee_status: "Employee Status",
    dashboard_recent_alerts: "Recent Alerts",
    dashboard_new_process: "New Process",
    analytics_title: "Onboarding Report",
    analytics_subtitle: "Overall progress of your company's onboarding processes.",
    analytics_company: "Company",
    analytics_session_company: "Session company",
    analytics_from: "From",
    analytics_to: "To",
    analytics_apply_filters: "Apply filters",
    analytics_export: "Export",
    analytics_total_onboardings: "Total onboardings",
    analytics_completed: "Completed",
    analytics_in_progress: "In progress",
    analytics_delayed: "Delayed",
    analytics_average_days: "Average days",
    analytics_no_average: "No data",
    analytics_detail_title: "Onboarding detail",
    analytics_records: "records",
    analytics_employee: "Employee",
    analytics_process: "Process",
    analytics_role: "Role",
    analytics_start_date: "Start date",
    analytics_end_date: "End date",
    analytics_status: "Status",
    analytics_progress: "Progress",
    analytics_tasks: "Tasks",
    analytics_total_tasks: "Total tasks",
    analytics_completed_tasks: "Completed tasks",
    analytics_delayed_tasks: "Delayed tasks",
    analytics_delayed_short: "delayed",
    analytics_completion_days: "Completion days",
    analytics_error_loading: "The onboarding report could not be loaded.",
    
    portal_admin: "Admin Portal",
    portal_employee: "Employee Portal",
    
    modal_ajustes_title: "System Settings",
    modal_ajustes_appearance: "Appearance",
    modal_ajustes_language: "Language",
    theme_light: "Light",
    theme_dark: "Dark",
    theme_system: "System",
    
    btn_close: "Close",
    btn_save: "Save",
    btn_cancel: "Cancel",
    btn_delete: "Delete",
    btn_add: "Add",
    btn_edit: "Edit",
    btn_assign: "Assign",
    btn_track: "Track",
    btn_complete: "Complete",
    
    table_id: "ID",
    table_name: "Name",
    table_email: "Email",
    table_role: "Role",
    table_company: "Company",
    table_status: "Status",
    table_actions: "Actions",
    table_location: "Location",
    table_tasks: "Tasks",
    table_process: "Process",
    
    status_active: "Active",
    status_inactive: "Inactive",
    status_all_records: "All",
    filter_record_status: "Filter by status",
    
    msg_confirm_delete: "Are you sure you want to delete this item?",
    msg_success_delete: "Successfully deleted",
    msg_error_generic: "An error occurred",
    msg_loading: "Loading...",
    msg_no_data: "No data found.",
    msg_success_assign: "✅ Onboarding assigned successfully!",
    msg_error_assign: "❌ Error assigning onboarding.",
    msg_success_complete: "✅ Task completed successfully",
    employee_portal_title: "My Onboarding",
    employee_portal_welcome: "Welcome",
    employee_portal_process: "Onboarding process",
    employee_portal_no_journey: "You do not have an onboarding process assigned at this moment.",
    employee_portal_missing_email: "We could not find an email associated with your session.",
    employee_portal_error: "We could not load your onboarding portal.",
    employee_portal_task_error: "Error completing the task.",
    employee_portal_open_resource: "Open resource",
    employee_portal_deadline: "Due",
    employee_portal_overdue: "Overdue",
    employee_portal_completing: "Completing...",
    
    // Processes
    processes_kpi_total: "Total Processes",
    processes_kpi_progress: "In Progress",
    processes_kpi_completed: "Completed",
    processes_role_view: "Role View",
    processes_col_employee: "Employee",
    processes_col_area: "Area",
    processes_col_role: "Role",
    processes_col_progress: "Progress",
    processes_col_start: "Start Date",
    processes_col_end: "End Date",
    processes_col_location: "Location",
    processes_col_actions: "Actions",
    processes_btn_detail: "View Detail",
    processes_modal_title: "Progress of",
    processes_modal_task: "Task",
    processes_modal_status: "Status",
    processes_modal_evidence: "Evidence",
    processes_modal_completed: "Completed",
    processes_modal_pending: "Pending",
    processes_modal_download: "Download Evidence",
    processes_modal_no_evidence: "No evidence",
    processes_modal_no_journey: "No active onboarding process assigned to this employee.",
    processes_empty_state: "There are no active onboarding processes at this moment",
    processes_loading: "Loading processes...",
    
    // User filters
    filter_name: "Filter by Name",
    filter_email: "Filter by Email",
    filter_role: "Filter by Role",
    filter_onboarding_status: "Filter by Onboarding Status",
    filter_all_statuses: "All statuses",
    filter_unassigned: "Unassigned",
    filter_in_progress: "In Progress",
    filter_completed: "Completed",
    users_showing_count: "Showing",
    users_showing_of: "of",
    users_showing_users: "users",
    users_per_page: "Users per page:",
    users_page_indicator: "Page",
    users_page_of: "of",
    
    // Company form
    company_new_title: "New Company",
    company_edit_title: "Edit Company",
    company_country: "Country",
    company_region_chile: "Region",
    company_region_mexico: "State",
    company_region_colombia: "Department",
    company_region_argentina: "Province",
    company_region_peru: "Department",
    company_region_default: "Region/State",
    company_city_commune: "City / District",
    company_city_commune_placeholder: "Type city or district...",
    company_delete_confirm: "Are you sure you want to delete this company? This action cannot be undone.",
    company_delete_success: "Company successfully deleted",
    processes_subtitle: "Control and monitoring of induction and onboarding processes.",
    processes_admin_view: "Viewing all onboarding processes of the company.",
    processes_supervisor_view: "Viewing processes under your direct supervision.",
    processes_encargado_view: "Viewing processes of the area:",
    processes_user_id: "User ID",
    location_remote: "Remote",
    processes_modal_progress_general: "General Progress",
    processes_group_custom: "Custom / No Template Processes",
    processes_btn_delete: "Delete Process",
    processes_custom_desc: "Individual journeys without a base template or with a deleted template",
    processes_no_desc: "No description available",
    processes_colaborador: "employee",
    processes_colaboradores: "employees",
    filter_name_placeholder: "Search name...",
    filter_email_placeholder: "Search email...",
    filter_all_roles: "All roles",
    btn_previous: "Previous",
    btn_next: "Next",
    stage_label: "Stage",
    label_area: "Area",
    label_location: "Location",
    label_country: "Country",
    label_city: "City",
    label_commune: "District",
    label_office_branch: "Branch / Office",
    btn_new_area: "+ New Area",
    btn_delete_area: "Delete Area",
    placeholder_area_name: "Area name...",
    select_area_placeholder: "-- Select Area --",
    select_office_placeholder: "-- Select Branch --",
    btn_new_office: "+ New",
    placeholder_office_name: "Branch name...",
    placeholder_country: "e.g. Chile",
    placeholder_city: "e.g. Santiago",
    placeholder_commune: "e.g. Providencia",
    placeholder_password_optional: "Leave blank to keep unchanged",
    label_password_optional: "Password (Optional)",
    btn_assign_employee: "Assign Employee",
    assign_onboarding_title: "Assign Onboarding",
    assign_onboarding_to: "To",
    warning_label: "Warning",
    warning_active_journey: "This employee already has an active onboarding process. You can assign a new process anyway to link stages.",
    table_template: "Template",
    label_mentor_supervisor: "Mentor / Supervisor",
    select_template_placeholder: "Select template...",
    select_supervisor_placeholder: "Select supervisor...",
    btn_confirm_journey: "Confirm Journey",
    assign_employee_supervise_title: "Assign Employee to Supervise",
    supervisor_area_label: "Supervisor's Area",
    no_area_label: "No Area",
    select_employee_area_placeholder: "Select an employee from your area...",
    assign_supervisor_help_text: "Only active employees in the same area who have an onboarding process are shown.",
    msg_error_no_active_journey: "The selected employee does not have an active process.",
    msg_success_assign_supervisor: "Supervisor successfully assigned.",
    msg_error_assign_supervisor: "Error assigning supervisor.",
    users_edit_title: "Edit User",
    users_edit_subtitle: "Update the user's profile details.",
    users_no_filter_match: "No users found matching the applied filters",
    error_create_office: "Error creating branch",
    error_create_area: "Error creating area",
    error_delete_area: "Error deleting area",
    confirm_delete_area: "Are you sure you want to delete this area?",
    confirm_delete_user: "Are you sure you want to delete this user?",
    error_create_user: "Error creating user.",
    error_update_user: "Error updating user.",
    error_delete_user: "Error deleting user.",
    msg_user_create_success: "User successfully created.",
    msg_user_update_success: "User successfully updated.",
    msg_user_delete_success: "User successfully deleted.",
    table_document: "Document",
    msg_no_file: "No file",
    select_company_placeholder: "Select Company...",
    label_parent_template: "Parent binding process",
    option_none_parent_template: "None (Initial Process)",
    help_parent_template: "Allows chaining onboardings longer than 31 days.",
    error_save_template: "Error saving template",
    template_edit_title: "Edit Onboarding Template",
    template_new_title: "New Onboarding Template",
    template_settings_title: "Template Settings",
    template_name_label: "Template Name",
    btn_save_template: "Save Template",
    onboarding_steps_title: "Onboarding Steps",
    btn_add_step: "Add Step",
    placeholder_task_title: "Task Title (e.g. Welcome Meeting)",
    placeholder_resource_url: "Link to Document or Video (e.g. Drive, YouTube)",
    placeholder_task_description: "Brief description of what the employee should do...",
    placeholder_sla_days: "SLA (days)",
    label_sla_days: "Maximum days to complete this step (1-365). Empty = no deadline.",
    label_evidence_mandatory: "Must the employee submit evidence to complete this task?",
    btn_move_up: "Move Up",
    btn_move_down: "Move Down",
    task_type_read_text: "Read Text (Welcome)",
    task_type_read_document: "View Document / External Link",
    task_type_watch_video: "Watch Video",
    task_type_upload_document: "Upload Document (Employee)",
    error_delete_company: "Error deleting company. Make sure there are no remaining users or processes associated with this company.",
    mobile_access_title: "Employee Access",
    mobile_email_label: "Company Email",
    mobile_btn_enter: "Enter Onboarding",
    mobile_user_not_found: "User not found or connection error",
    mobile_task_completed_success: "✅ Task successfully completed",
    mobile_task_completed_error: "Error completing task",
    mobile_default_description: "Please complete this step to continue.",
    mobile_btn_watch_video: "📺 Watch Video",
    mobile_btn_open_resource: "📖 Open Resource",
    mobile_upload_evidence_label: "Upload document (PDF, JPG, PNG)",
    mobile_task_completed_badge: "✅ Task completed",
    mobile_status_uploading: "Uploading...",
    mobile_status_completing: "Completing...",
    mobile_btn_complete: "Complete",
    mobile_btn_back_web: "← Back to web view",
    mobile_status_completed: "Completed",
    mobile_status_overdue: "Overdue",
    mobile_status_pending: "Pending",
    mobile_label_due: "Due:",
    mobile_btn_open_task: "Open Task",
    mobile_nav_home: "Home",
    mobile_nav_tasks: "Tasks",
    mobile_nav_files: "Files",
    mobile_nav_profile: "Profile",
    mobile_greeting: "Hi",
    error_invalid_credentials: "Invalid credentials",
    badge_overdue: "Overdue",
    badge_completed: "Completed",
    badge_pending: "Pending",
    dashboard_task_vence: "Due",
    dashboard_tasks_pendientes: "Pending Tasks",
    dashboard_progreso_general: "General Progress",
    dashboard_detalles_proceso: "Process Details",
    dashboard_empleado: "Employee",
    dashboard_rol: "Role",
    dashboard_progreso: "Progress",
    dashboard_tareas_proceso: "Process Tasks",
    dashboard_no_tareas: "No tasks registered for this process.",
    dashboard_mas_tareas: "more tasks",
    dashboard_todas_completadas: "All tasks completed!",
    dashboard_no_onboardings: "No onboarding processes in progress.",
    alert_overdue_task: "Overdue Task",
    alert_type_sla_expired: "Expired SLA",
    alert_time_overdue: "Overdue",
    alert_time_recent: "Recent",
    alert_no_pending: "No pending alerts.",
    alerts_subtitle: "Track overdue tasks and attended alerts",
    alerts_refresh: "Refresh",
    alerts_active: "Active",
    alerts_history: "History",
    alerts_search: "Search alert",
    alerts_employee: "Employee",
    alerts_task: "Task",
    alerts_deadline: "Deadline",
    alerts_days_overdue: "Days overdue",
    alerts_generated_at: "Generated",
    alerts_status: "Status",
    alerts_pending: "Pending",
    alerts_attended: "Attended",
    alerts_attend: "Attend",
    alerts_days: "day(s)",
    alerts_no_history: "No attended alerts in history.",
    alerts_error_load: "Alerts could not be loaded.",
    alerts_error_attend: "The alert could not be attended.",
    alerts_error_user: "The current user could not be identified to attend the alert.",
    filter_by_area: "Filter by Area",
    all_areas: "All Areas",
    modal_ajustes_tab_preferences: "Preferences",
    modal_ajustes_tab_areas: "Company Areas",
    modal_ajustes_tab_offices: "Branches / Offices",
    select_country_placeholder: "-- Select Country --",
    select_city_placeholder: "-- Select City/State --",
    loading_areas: "Loading areas...",
    no_areas_configured: "No areas configured for your company.",
    loading_offices: "Loading branches/offices...",
    no_offices_configured: "No branches or offices configured.",
    confirm_delete_office: "Are you sure you want to delete this branch/office?",
    error_load_areas: "Error loading company areas.",
    error_update_area: "Error updating area.",
    error_load_offices: "Error loading company branches/offices.",
    error_delete_office: "Error deleting branch/office.",
    error_update_office: "Error updating branch/office.",
  }
};

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('onboardhub_lang') || 'es';
  });

  useEffect(() => {
    localStorage.setItem('onboardhub_lang', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    let value = translations[language];
    if (value && value[key]) {
      return value[key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
